### ISSUE TITLE
运行的时候报错呀  是jar包的事吗

### ISSUE THREAD

**Issue by 0532** [snailxr/quartz-spring_demo#1]
Caused by: org.apache.ibatis.binding.BindingException: Invalid bound statement (not found): com.snailxr.base.task.dao.ScheduleJobMapper.getAll
    at org.apache.ibatis.binding.MapperMethod$SqlCommand.<init>(MapperMethod.java:178)
    at org.apache.ibatis.binding.MapperMethod.<init>(MapperMethod.java:38)
    at org.apache.ibatis.binding.MapperProxy.cachedMapperMethod(MapperProxy.java:49)
    at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:42)
    at com.sun.proxy.$Proxy10.getAll(Unknown Source)
    at com.snailxr.base.task.service.JobTaskService.init(JobTaskService.java:157)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:344)
    at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:295)
    at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:130)
    ... 57 more

**Comment by snailxr** [comment]
使用的maven构建的项目吗？

**Comment by 0532** [comment]
对 是用maven构建的  运行的时候报错
[2015-06-11 03:23:22,009] Artifact quartz-spring_demo:war exploded: Error during artifact deployment. See server log for details.
那个详细日志 就是 我上面贴的，thx
